name: CD Pipeline

on:
 workflow_run:
   workflows: ["CI Pipeline"]
   types:
    - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: pull from docker
      run: sudo docker pull jackson216/cicd-pipeline:latest
    - name: Delete OLd docker container
      run: sudo docker rm -f cicd-pipeline-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container jackson216/cicd-pipeline   
     