name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted  # Use your EC2 self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use single checkout, updated to v4

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t cicd-pipeline .
    
      - name: Push the Docker image to Docker Hub
        run: docker push jackson212/cicd-pipeline:latest
